model_name: ["ResNet-18", "ViT-Tiny"] 
optimizer_name: ["adam", "sgd", "adam-mini", "adamw", "adafactor", "lion"]

hyperparametres_general:
  batch_size: [ 256, 512, 1024, 2048]
  epochs: 300
  scheduler: cosine
  warmup: linear
  warmup_epochs: 5
  T_max: 300
  eta_min: !!float 1e-5

datasets:
  cifar10:
    num_classes: 10
    patience_resnet: 15
    patience_tiny: 30

    vit_specific:
      label_smoothing: 0.1

  cifar100:
    num_classes: 100
    patience_resnet: 20
    patience_tiny: 35

    vit_specific:
      label_smoothing: 0.15


vit_specific:
  patch_size: 4
  warmup_epochs: 5
  warmup_type: linear
  label_smoothing: 0.1
  drop_path_rate: 0.1


#################################
# SGD
#################################

sgd:
  # ResNet-18
  resnet:
    lr: !!float 5e-2
    momentum: 0.9
    nesterov: true
    weight_decay: !!float 5e-4

  # ViT-Tiny
  vit:
    lr: !!float 3e-4
    momentum: 0.9
    nesterov: true
    weight_decay: !!float 5e-4





#################################
# Adam
#################################

adam:
  # ResNet-18
  resnet:
    lr: !!float 1e-3
    betas: [0.9, 0.999]
    eps: !!float 1e-8
    weight_decay: 0.0

  # ViT-Tiny
  vit:
    lr: !!float 5e-4
    betas: [0.9, 0.999]
    eps: !!float 1e-8
    weight_decay: 0.0



#################################
# AdamW
#################################

adamw:
  # ResNet-18
  resnet:
    lr: !!float 1e-3
    betas: [0.9, 0.999]
    eps: !!float 1e-8
    weight_decay: !!float 1e-4

  # ViT-Tiny
  vit:
    lr: !!float 8e-4
    betas: [0.9, 0.999]
    eps: !!float 1e-8
    weight_decay: !!float 0.05



#################################
# Adafactor
#################################

adafactor:

  # ResNet-18
  resnet:
    lr: !!float 1e-3
    beta1: 0.9
    decay_rate: -0.8
    eps: [!!float 1e-30, !!float 1e-3]
    relative_step: false
    scale_parameter: false
    weight_decay: !!float 1e-4

  # ViT-Tiny
  vit:
    lr: !!float 5e-4
    beta1: 0.9
    decay_rate: -0.8
    eps: [!!float 1e-30, !!float 1e-3]
    relative_step: false
    scale_parameter: false
    weight_decay: 0.0



#################################
# Lion
#################################

lion:

  # ResNet-18
  resnet:
    lr: !!float 3e-4
    betas: [0.9, 0.99]
    weight_decay: !!float 1e-4

  # ViT-Tiny
  vit:
    lr: !!float 3e-4
    betas: [0.9, 0.99]
    weight_decay: !!float 0.05




#################################
# Adam-mini
#################################

adam-mini:

  # ResNet-18
  resnet:
    lr: !!float 1e-3
    betas: [0.9, 0.999]
    eps: !!float 1e-8
    weight_decay: !!float 1e-4
    n_heads: 1
    n_kv_heads: 1


  # ViT-Tiny
  vit:
    lr: !!float 7e-4
    betas: [0.9, 0.999]
    eps: !!float 1e-8
    weight_decay: !!float 0.02
    n_heads: 3
    n_kv_heads: 3
